---
title: "Challenge 05(z)"
author: "Landon Porter"
date: "4/1/2022"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)

#CHALLENGE 1 

d <- read_csv("D:/BACK-UP'/documents'/UT AUSTIN/Spring 2022/ANT388 (R-coding)/git-hub/week5/IMBD-movie-data.txt", col_names = TRUE)
str(d)

# Use a one-line statement to filter the dataset to include just movies from 1920 to 1979 and movies that are between 1 and 3 hours long (runtimeMinutes >= 60 and runtimeMinutes <= 180), and add a new column that codes the startYear into a new variable, decade (“20s,” “30s,” …“70s”). If you do this correctly, there should be 5651 movies remaining in the dataset.

df <- d %>% filter(startYear %in% 1920:1979 & runtimeMinutes %in% 60:180) %>% 
  mutate(decade = case_when(startYear %in% 1920:1929 ~ "20's", startYear %in% 1930:1939 ~ "30's", startYear %in% 1940:1949 ~ "40's", startYear %in% 1950:1959 ~ "50's", startYear %in% 1960:1969 ~ "60's", startYear %in% 1970:1979 ~ "70's"))



#Use {ggplot2} (which is part of {tidyverse}) to plot histograms of the distribution of runtimeMinutes for each decade.
library(cowplot)
library(ggplot.multistats)
library(ggplot2)

p <- ggplot(data = df) 
p <- p + geom_histogram(
  aes(x = runtimeMinutes, color=factor(decade), binwidth= 30, na.rm = TRUE)
)
p
p <- p + facet_wrap(~decade, ncol= 4)
p


#Use a one-line statement to calculate the population mean and population standard deviation in runtimeMinutes for each decade and save the results in a new dataframe called results

results <- df %>% group_by(decade)%>% 
  summarize(
    pop_mean = mean(runtimeMinutes, na.rm = TRUE),
    pop_sd = sd(runtimeMinutes, na.rm = TRUE),
    pop_se = pop_sd/sqrt(100)
  )
results #pop mean, sd, and se for runtimeMinutes  #does se for population make sense? se only for sample? 



#Draw a single sample of 100 movies, without replacement, from each decade and calculate the single sample mean and single sample standard deviation in runtimeMinutes for each decades. Recall that your single sample mean for each decade is an estimate of the population mean for each decade.

n = 100 #(sample size = 100)
samp_byDecade <- group_by(df, decade) %>% 
  sample_n(n, replace = FALSE) %>%
  summarize(
    samp_mean = mean(runtimeMinutes, na.rm =TRUE),
    samp_sd = sd(runtimeMinutes, na.rm =TRUE),
    samp_se = samp_sd / sqrt(n)
  ) #(pulls a single sample, of 100 movies, from each decade and calculates runtime stats (i.e. mean, sd, se) for each decade)

samp_byDecade 




#Compare these estimates to the actual population mean runtimeMinutes for each decade and to the calculated SE in the population mean for samples of size 100 based on the population standard deviation for each decade.

comparison <- left_join(samp_byDecade, results, by ="decade")
print(comparison)




#Generate a sampling distribution of mean runtimeMinutes for each decade by [a] drawing 1000 samples of 100 movies from each decade and, for each sample, [b] calculating the mean runtimeMinutes and the standard deviation in runtimeMinutes for each decade. Use either a standard for( ){ } loop, the do(reps) * formulation from {mosaic}, the rerun() function from {purrr}, or the rep_sample_n() workflow from {infer} to generate your these sampling distributions.

#[a]
library(mosaic)
n <- 100
reps <- 1000

s <- {do(reps) * sample_n(group_by(df, decade), n, replace=FALSE)} %>% 
  group_by(decade, .index) %>%
  summarise(avg_runtimeMinutes = mean(runtimeMinutes, na.rm = TRUE), sd_runtimeMinutes = sd(runtimeMinutes, na.rm = TRUE))

(p <- ggplot(data=s, aes(avg_runtimeMinutes)) +
    geom_histogram(stat = "bin",
      bins=25,
      colour="black",
      fill="pink") +
    facet_wrap(~ decade, scales = "free_x"))

#sample distributions are close to being normal 





#Finally, compare the standard error in runtimeMinutes for samples of size 100 from each decade [1] as estimated from your first sample of 100 movies, [2] as calculated from the known population standard deviations for each decade, and [3] as estimated from the sampling distribution of sample means for each decade.

library(kableExtra)

samp_dist_stats <- s %>%
  group_by(decade) %>%
  summarize(samp_dist_mean=mean(avg_runtimeMinutes),
  samp_dist_sd=sd(avg_runtimeMinutes))

comparison <- inner_join(results, samp_dist_stats, by = "decade") %>%
  select(decade, pop_se, samp_se, samp_sd)

kable(comparison, digits = 3) %>%
  kable_styling(font_size = 12, full_width = FALSE)










```








```{r}
library(tidyverse)

#CHALLENGE 2 

f <- "https://raw.githubusercontent.com/difiore/ada-2022-datasets/main/zombies.csv"
d <- read_csv(f, col_names = TRUE)

#Calculate the population mean and standard deviation for each quantitative random variable in the dataset (height, weight, age, number of zombies killed, and years of education).

alive <- select(d, "gender", "height", "weight", "age",
  "zombies_killed", "years_of_education")
print(head(alive))

pop_mean <- alive %>%
  dplyr::summarise(across(
    c(height, weight, age, zombies_killed, years_of_education),
    mean))

pop_sd <- alive %>%
  dplyr::summarise(across(
    c(height, weight, age, zombies_killed, years_of_education),
    sd))
print(pop_mean)
print(pop_sd)



#Use {ggplot} and make boxplots of each of these variables by gender.
library(tidyverse)
library(cowplot)
library(ggplot.multistats)
library(ggplot2)

p1 <- ggplot(data=d,aes(x=gender, y=height))
p1 <- p1 + geom_boxplot(aes(colour=factor(gender)))
p1 <- p1 + theme(legend.position="none")

p2 <- ggplot(data=d,aes(x=gender, y=weight))
p2 <- p2 + geom_boxplot(aes(colour=factor(gender)))
p2 <- p2 + theme(legend.position="none")

p3 <- ggplot(data=d,aes(x=gender, y=age))
p3 <- p3 + geom_boxplot(aes(colour=factor(gender)))
p3 <- p3 + theme(legend.position="none")

p4 <- ggplot(data=d,aes(x=gender, y=zombies_killed))
p4 <- p4 + geom_boxplot(aes(colour=factor(gender)))
p4 <- p4 + theme(legend.position="none")

p5 <- ggplot(data=d,aes(x=gender, y=years_of_education))
p5 <- p5 + geom_boxplot(aes(colour=factor(gender)))
p5 <- p5 + theme(legend.position="none")

plot_grid(p1, p2, p3, p4, p5, nrow = 2)



#make scatter plots of height and weight in relation to age (i.e., use age as the x variable), using different colored points for males versus females. Do these variables seem to be related? In what way?

p1 <- ggplot(data = alive,
  aes(x = age, y = height, colour = factor(gender))) +
  geom_point() +
  theme(legend.position = "top", legend.title = element_blank())
p2 <- ggplot(data = alive,
  aes(x = age, y = weight, colour = factor(gender))) +
  geom_point() +
  theme(legend.position = "top", legend.title = element_blank())

plot_grid(p1, p2, nrow = 1)
#variables of height and weight show the expected linear correlation with age. I.e. that as age increase so does height and weight. If this was continued out to later ages we would not see such a positive correlation. 




#Using histograms and Q-Q plots, check whether the quantitative variables seem to be drawn from a normal distribution.

library(ggpubr)
p1 <- ggplot(data = d, aes(x=height)) +
  geom_histogram(bins = 30) + ggtitle("Height")
p2 <- ggqqplot(data = d, x="height")


p3 <- ggplot(data = d, aes(x=weight)) +
  geom_histogram(bins = 30) + ggtitle("Weight")
p4 <- ggqqplot(data = d, x="weight")


p5 <- ggplot(data = d, aes(x=age)) +
  geom_histogram(bins = 30) + ggtitle("Age")
p6 <- ggqqplot(data = d, x="age")


p7 <- ggplot(data = d, aes(x=zombies_killed)) +
  geom_histogram(binwidth = 1) + ggtitle("Zombies Killed")
p8 <- ggqqplot(data = d, x="zombies_killed")


p9 <- ggplot(data = d, aes(x=years_of_education)) +
  geom_histogram(binwidth = 1) + ggtitle("Years of Education")
p10 <- ggqqplot(data = d, x="years_of_education")

plot_grid(p1, p3, p5, p2, p4, p6, nrow = 2)
plot_grid(p7, p9, p8, p10, nrow = 2)


#use the sample_n() function from {dplyr} to sample ONE subset of 50 zombie apocalypse survivors (without replacement) from this population and calculate the mean and sample standard deviation for each variable. Also estimate the standard error for each variable based on this sample and use that to construct a 95% confidence interval for each mean.





#first set up functions for se and ci 

SE <- function(x, type="normal") {
  if (type=="normal"){
    SE <- sd(x)/sqrt(length(x))
  }
  if (type=="poisson"){
    SE <- sqrt(mean(x)/length(x))
    # mean(x) is estimate of lambda
  }
  return(SE)
}

# confidence interval based on normal distribution
CI_norm <- function(x, alpha = 0.05) {
  CI <- mean(x) + c(1) * qnorm(1 - alpha/2) * SE(x)
  names(CI) <- c("CI norm U")
  return(CI)
}

CI_t <- function(x, alpha = 0.05) {
  CI <- mean(x) + c(-1,1) * qt(1 - alpha/2, length(x) - 1) * SE(x)
  # confidence interval based on t distribution
  names(CI) <- c("CI t L","CI t U")
  return(CI)
}


#next define sample for stats 
n <- 50
s <- sample_n(d, size = n, replace = FALSE)
print(s)

#run stats
samp_1_means <- s %>% dplyr::summarise(across(
  .cols = c(height, weight, age, zombies_killed, years_of_education),
  .fns = ~ mean(.)))

samp_1_SDs <- s %>% dplyr::summarise(across(
  .cols = c(height, weight, age, zombies_killed, years_of_education),
  .fns = ~ sd(.)))

samp_1_SEs <- s %>% dplyr::summarise(across(
    .cols = c(height, weight, age),
    .fns = ~ SE(., type = "normal")),
  across(
    .cols = c(zombies_killed, years_of_education),
    .fns = ~ SE(., type = "poisson")))

samp_1_CI_norm <- s %>%
  dplyr::summarise(across(
    .cols = c(height, weight, age, zombies_killed, years_of_education),
    .fns = ~ CI_norm(.)))

#make a table 
library(kableExtra)

samp_1_summary <- as_tibble(t(bind_rows(samp_1_means, samp_1_SDs,
  samp_1_SEs, samp_1_CI_norm)),
  .name_repair = "minimal")
names(samp_1_summary) <- c("Samp 1 Mean", "Samp 1 SD",
  "Samp 1 SE", "Samp 1 CI norm L", "Samp 1 CI norm U")
variables <- tibble(Variable = c("Height", "Weight", "Age", "Kills", "Years of Ed"))

samp_1_summary <- bind_cols(variables, samp_1_summary)

kable(samp_1_summary, digits = 3) %>%
  kable_styling(font_size = 12, full_width = FALSE)


#Then draw another 199 random samples of 50 zombie apocalypse survivors out of the population and calculate the mean for each of the these samples. 
#What are the means and standard deviations of the sampling distribution for each variable? 


library(mosaic)
set.seed(1) #randomly pull sample
a <- 199

#create a new tibble
survivors199 <- tibble(
  z_seq = c(1:a),
  height_mean = do(a) * mean(~height, data = sample_n(d, size = n, replace = FALSE)),
  weight_mean = do(a) * mean(~weight, data = sample_n(d, size = n, replace = FALSE)),
  a_mean = do(a) * mean(~age, data = sample_n(d, size = n, replace = FALSE)),
  zk_mean = do(a) * mean(~zombies_killed, data = sample_n(d, size = n, replace = FALSE)),
  ed_mean = do(a) * mean(~years_of_education, data = sample_n(d, size = n, replace = FALSE))
  )
survivors199


#alternativly

k <- 199  
additional_samples <- do(k) * sample_n(d, size = n, replace = FALSE)
s <- mutate(s, .row = 1:n, .index = k + 1)
all_s <- bind_rows(additional_samples, s)

samp_dist <- all_s %>%
    group_by(.index) %>%
    dplyr::summarise(across(.cols = c(height, weight, age, zombies_killed, years_of_education),
        .fns = ~mean(.))) %>%
    select(-.index)

samp_SEs <- all_s %>%
    group_by(.index) %>%
    dplyr::summarise(across(.cols = c(height, weight, age), .fns = ~SE(., type = "normal")),
        across(.cols = c(zombies_killed, years_of_education), .fns = ~SE(., type = "poisson"))) %>%
    select(-.index)


samp_dist_means <- samp_dist %>%
    dplyr::summarise(across(.cols = everything(), .fns = ~mean(.)))

samp_dist_SDs <- samp_dist %>%
    dplyr::summarise(across(.cols = everything(), .fns = ~sd(.)))

# make a pretty table
samp_dist_summary <- as_tibble(t(bind_rows(samp_dist_means, samp_dist_SDs)), .name_repair = "minimal")
names(samp_dist_summary) <- c("Samp Dist Mean", "Samp Dist SD")
variables <- tibble(Variable = c("Height", "Weight", "Age", "Kills", "Years of Ed"))

samp_dist_summary <- bind_cols(variables, samp_dist_summary)

kable(samp_dist_summary, digits = 3) %>%
    kable_styling(font_size = 12, full_width = FALSE)

#How do the standard deviations of the sampling distribution for each variable compare to the standard errors estimated from your first sample of size 50?

samp_SE_means <- samp_SEs %>%
    dplyr::summarise(across(.cols = everything(), .fns = ~mean(.)))

compare_SEs <- tibble(Variable = c("Height", "Weight", "Age", "Kills", "Years of Ed"),
    `Samp Dist Mean` = samp_dist_summary$`Samp Dist Mean`, `**Samp Dist SD**` = samp_dist_summary$`Samp Dist SD`,
    `SE est from Pop SD` = t(pop_sd/sqrt(n)), `**SE est from Sample 1**` = samp_1_summary$`Samp 1 SE`,
    `Mean SEs Across Samples` = t(samp_SE_means))

#make the table 
rownames(compare_SEs) <- NULL  # get rid of nownames 
kable(compare_SEs, digits = 3) %>%
    kable_styling(font_size = 12, full_width = FALSE)




#What do sampling distributions for each variable mean look like? Are they normally distributed? What about for those variables that you concluded were not originally drawn from a normal distribution?

p1 <- ggplot(data = samp_dist, aes(x = height)) + geom_histogram(bins = 10) + ggtitle("Height Means")
p2 <- ggqqplot(data = samp_dist, x = "height")
p3 <- ggplot(data = samp_dist, aes(x = weight)) + geom_histogram(bins = 10) + ggtitle("Weight Means")
p4 <- ggqqplot(data = samp_dist, x = "weight")
p5 <- ggplot(data = samp_dist, aes(x = age)) + geom_histogram(bins = 10) + ggtitle("Age Means")
p6 <- ggqqplot(data = samp_dist, x = "age")
p7 <- ggplot(data = samp_dist, aes(x = zombies_killed)) + geom_histogram(bins = 10) +
    ggtitle("Zombies Killed Means")
p8 <- ggqqplot(data = samp_dist, x = "zombies_killed")
p9 <- ggplot(data = samp_dist, aes(x = years_of_education)) + geom_histogram(bins = 10) +
    ggtitle("Years of Education Means")
p10 <- ggqqplot(data = samp_dist, x = "years_of_education")

plot_grid(p1, p3, p5, p2, p4, p6, nrow = 2)
plot_grid(p7, p9, p8, p10, nrow = 2)



#These all appear to be normally distibuted. The varibales that initially were not normal in their distribution now appear normal. This is a conseqence of K being a high number. 







#*Finally*, construct a 95% confidence interval for each mean directly from the sampling distribution of sample means using the central 95% that distribution. 


samp_dist_CI_L <- dplyr::summarise(samp_dist, across(.cols = everything(), .fns = ~quantile(.,
    alpha/2)))

samp_dist_CI_U <- dplyr::summarise(samp_dist, across(.cols = everything(), .fns = ~quantile(.,
    1 - alpha/2)))

samp_dist_summary_w_CI <- bind_cols(samp_dist_summary, t(samp_dist_CI_L), t(samp_dist_CI_U),
    .name_repair = "minimal")

names(samp_dist_summary_w_CI) <- c("Variable", "Samp Dist Mean", "Samp Dist SD",
    "Samp Dist CI L", "Samp Dist CI U")

kable(samp_dist_summary_w_CI, digits = 3) %>%
    kable_styling(font_size = 12, full_width = FALSE)



# Compare the CIs based on one sample and the corresponding sample standard deviation versus the CI based on simulation where you created a sampling distribution across 200 samples

compare_CIs <- select(samp_1_summary, -c(`Samp 1 Mean`, `Samp 1 SD`, `Samp 1 SE`)) %>%
    bind_cols(`Samp Dist CI L` = samp_dist_summary_w_CI$`Samp Dist CI L`, `Samp Dist CI U` = samp_dist_summary_w_CI$`Samp Dist CI U`)
kable(compare_CIs, digits = 3) %>%
    kable_styling(font_size = 12, full_width = FALSE)


#The CI are basically equivalent despite being derived from different methods(i.e. resampling vs parametric vs bootstrapping). 


```

